name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: echo
      run: echo ${{ github.ref }}
    - name: test
      if: startsWith(github.ref, 'refs/heads/stable')
      run: echo gottem

